FROM ubuntu:16.04 as builder
WORKDIR /home/weave
ARG SCOPE_SKIP_UI_ASSETS
RUN apt-get update
RUN apt-get install -y make git wget gcc libpcap-dev time
RUN if [ `uname -m` = "aarch64" ] ; then \
       export ARCH="arm64"; \
    elif [ `uname -m` = "s390x" ] ; then \
       export ARCH="s390x"; \
    else \
       export ARCH="amd64"; \
    fi && \
    wget -q https://dl.google.com/go/go1.13.linux-"${ARCH}".tar.gz && \
    tar -xf go1.13.linux-"${ARCH}".tar.gz && \
    mv go /usr/local
WORKDIR /root/go/src/github.com/weaveworks
COPY / scope
WORKDIR scope
ENV GOROOT=/usr/local/go
ENV GOPATH=/root/go
ENV PATH=$GOPATH/bin:$GOROOT/bin:$PATH
RUN go get -u github.com/mjibson/esc
RUN make BUILD_IN_CONTAINER=false GO_BUILD_INSTALL_DEPS= prog/scope

FROM alpine:3.11.3
WORKDIR /home/weave
RUN apk add --no-cache bash conntrack-tools iproute2 util-linux curl
COPY --from=builder /root/go/src/github.com/weaveworks/scope/prog/scope /home/weave/

ENTRYPOINT ["/home/weave/scope", "--mode=probe", "--no-app", "--probe.docker=true"]

ARG revision
LABEL works.weave.role="system" \
      maintainer="Weaveworks <help@weave.works>" \
      org.opencontainers.image.title="cloud-agent" \
      org.opencontainers.image.source="https://github.com/weaveworks/scope" \
      org.opencontainers.image.revision="${revision}" \
      org.opencontainers.image.vendor="Weaveworks"
